import {defineType, defineField} from 'sanity';

export const programmeType = defineType({
  name: 'programme',
  title: 'Programme (terrain + modèle)',
  type: 'document',
  groups: [
    {name: 'identite', title: 'Identité'},
    {name: 'commercial', title: 'Offre commerciale'},
    {name: 'specs', title: 'Caractéristiques'},
    {name: 'localisation', title: 'Localisation'},
    {name: 'visuel', title: 'Visuels'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Titre du programme',
      type: 'string',
      group: 'identite',
      description: 'Ex. Domaine du Périgord — Circle',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      group: 'identite',
      options: {source: 'title', maxLength: 80},
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow (sur-titre)',
      type: 'string',
      group: 'identite',
      description: 'Ex. Édition 2026 — N°01',
    }),
    defineField({
      name: 'tagline',
      title: 'Phrase d\'accroche',
      type: 'string',
      group: 'identite',
    }),
    defineField({
      name: 'modele',
      title: 'Modèle d\'hébergement',
      type: 'reference',
      to: [{type: 'lieu'}],
      group: 'identite',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'status',
      title: 'Statut',
      type: 'string',
      group: 'commercial',
      options: {
        list: [
          {title: 'Ouvert à la commercialisation', value: 'ouvert'},
          {title: 'Bientôt disponible', value: 'a_venir'},
          {title: 'Complet', value: 'complet'},
          {title: 'Brouillon (caché)', value: 'brouillon'},
        ],
        layout: 'radio',
      },
      initialValue: 'ouvert',
    }),
    defineField({
      name: 'lots_total',
      title: 'Nombre total de lots',
      type: 'number',
      group: 'commercial',
      validation: (r) => r.min(0),
    }),
    defineField({
      name: 'lots_disponibles',
      title: 'Lots disponibles',
      type: 'number',
      group: 'commercial',
      validation: (r) => r.min(0),
    }),
    defineField({
      name: 'date_livraison',
      title: 'Date de livraison',
      type: 'string',
      group: 'commercial',
      description: 'Ex. Q3 2026',
    }),
    defineField({
      name: 'prix_terrain',
      title: 'Prix du terrain (€)',
      type: 'number',
      group: 'commercial',
    }),
    defineField({
      name: 'prix_module',
      title: 'Prix du module (€)',
      type: 'number',
      group: 'commercial',
    }),
    defineField({
      name: 'prix_total',
      title: 'Prix total (€)',
      type: 'number',
      group: 'commercial',
      description: 'Calculé manuellement ou défini comme prix de package.',
    }),
    defineField({
      name: 'rendement_min',
      title: 'Rendement minimum (% net annuel)',
      type: 'number',
      group: 'commercial',
    }),
    defineField({
      name: 'rendement_max',
      title: 'Rendement maximum (% net annuel)',
      type: 'number',
      group: 'commercial',
    }),
    defineField({
      name: 'loyer_nuit_min',
      title: 'Loyer min par nuit (€)',
      type: 'number',
      group: 'commercial',
    }),
    defineField({
      name: 'loyer_nuit_max',
      title: 'Loyer max par nuit (€)',
      type: 'number',
      group: 'commercial',
    }),
    defineField({
      name: 'taux_occupation_cible',
      title: 'Taux d\'occupation cible (%)',
      type: 'number',
      group: 'commercial',
    }),
    defineField({
      name: 'surface_terrain_m2',
      title: 'Surface du terrain (m²)',
      type: 'number',
      group: 'specs',
    }),
    defineField({
      name: 'surface_module_m2',
      title: 'Surface du module (m²)',
      type: 'number',
      group: 'specs',
    }),
    defineField({
      name: 'capacite',
      title: 'Capacité',
      type: 'string',
      group: 'specs',
      description: 'Ex. 2 à 4 personnes',
    }),
    defineField({
      name: 'caracteristiques',
      title: 'Caractéristiques détaillées',
      type: 'array',
      group: 'specs',
      of: [
        {
          type: 'object',
          fields: [
            {name: 'label', title: 'Étiquette', type: 'string'},
            {name: 'value', title: 'Valeur', type: 'string'},
          ],
          preview: {
            select: {title: 'label', subtitle: 'value'},
          },
        },
      ],
    }),
    defineField({
      name: 'prestations_incluses',
      title: 'Prestations incluses',
      type: 'array',
      group: 'specs',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'plu_zonage',
      title: 'Zonage PLU',
      type: 'string',
      group: 'localisation',
      description: 'Ex. UH (zone d\'habitat) — Affiché côté investisseur.',
    }),
    defineField({
      name: 'region',
      title: 'Région',
      type: 'string',
      group: 'localisation',
      description: 'Ex. Dordogne, Ardèche, Lac d\'Annecy',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'commune',
      title: 'Commune',
      type: 'string',
      group: 'localisation',
    }),
    defineField({
      name: 'coordonnees_gps',
      title: 'Coordonnées GPS',
      type: 'geopoint',
      group: 'localisation',
    }),
    defineField({
      name: 'description',
      title: 'Description longue',
      type: 'array',
      of: [{type: 'block'}],
      group: 'identite',
    }),
    defineField({
      name: 'hero_image',
      title: 'Image principale (drone ou paysage)',
      type: 'image',
      options: {hotspot: true},
      group: 'visuel',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'galerie',
      title: 'Galerie',
      type: 'array',
      group: 'visuel',
      of: [
        {
          type: 'image',
          options: {hotspot: true},
          fields: [{name: 'alt', title: 'Texte alternatif', type: 'string'}],
        },
      ],
    }),
    defineField({
      name: 'plan_masse',
      title: 'Plan masse (PDF téléchargeable)',
      type: 'file',
      group: 'visuel',
      options: {accept: 'application/pdf,image/*'},
    }),
    defineField({
      name: 'video_drone_url',
      title: 'URL vidéo drone (YouTube ou Vimeo)',
      type: 'url',
      group: 'visuel',
    }),
    defineField({
      name: 'calendly_url',
      title: 'URL Calendly d\'appel expert pour ce programme',
      type: 'url',
      group: 'commercial',
      description: 'Optionnel. Si vide, le bouton renvoie vers le contact général.',
    }),
    defineField({
      name: 'meta_title',
      title: 'Meta title',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'meta_description',
      title: 'Meta description',
      type: 'text',
      rows: 3,
      group: 'seo',
    }),
    defineField({
      name: 'order',
      title: 'Ordre d\'affichage',
      type: 'number',
      group: 'identite',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      region: 'region',
      status: 'status',
      lots: 'lots_disponibles',
      total: 'lots_total',
      media: 'hero_image',
    },
    prepare({title, region, status, lots, total, media}) {
      const subtitle = [region, status, lots != null && total != null ? `${lots}/${total} lots` : null]
        .filter(Boolean)
        .join(' · ');
      return {title, subtitle, media};
    },
  },
  orderings: [
    {
      title: 'Ordre d\'affichage',
      name: 'orderAsc',
      by: [{field: 'order', direction: 'asc'}],
    },
    {
      title: 'Région A→Z',
      name: 'regionAsc',
      by: [{field: 'region', direction: 'asc'}],
    },
  ],
});
